<?php

#
# Copyright (c) 2006 Sun Microsystems, Inc.
#                         All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

# Make these a $colors array for easier globalizing in functions
$gray    = "#A0A0A0";
$dgray   = "#808080";
$lgray   = "#C0C0C0";
$llgray  = "#DEDEDE";
$lllgray = "#E8E8E8";
$lred    = "#FFC0C0";
$lgreen  = "#C0FFC0";
$lyellow = "#FFFFC0";
$white   = "#FFFFFF";

$align   = "center";

$thcolor  = $llgray;

$menu_width = '220px';
$ft_menu_width = '125px';

?>
